/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/brain_model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/brain_model.glb')
  return (
    <group position={[-91.65, -110.0, -87.49]} {...props} dispose={null}>
      <mesh geometry={nodes.Frontal_Pole.geometry} material={nodes.Frontal_Pole.material} />
      <mesh geometry={nodes.Insular_Cortex.geometry} material={nodes.Insular_Cortex.material} />
      <mesh geometry={nodes.Superior_Frontal_Gyrus.geometry} material={nodes.Superior_Frontal_Gyrus.material} />
      <mesh geometry={nodes.Middle_Frontal_Gyrus.geometry} material={nodes.Middle_Frontal_Gyrus.material} />
      <mesh geometry={nodes['Inferior_Frontal_Gyrus,_pars_triangularis'].geometry} material={nodes['Inferior_Frontal_Gyrus,_pars_triangularis'].material} />
      <mesh geometry={nodes['Inferior_Frontal_Gyrus,_pars_opercularis'].geometry} material={nodes['Inferior_Frontal_Gyrus,_pars_opercularis'].material} />
      <mesh geometry={nodes.Precentral_Gyrus.geometry} material={nodes.Precentral_Gyrus.material} />
      <mesh geometry={nodes.Temporal_Pole.geometry} material={nodes.Temporal_Pole.material} />
      <mesh geometry={nodes['Superior_Temporal_Gyrus,_anterior_division'].geometry} material={nodes['Superior_Temporal_Gyrus,_anterior_division'].material} />
      <mesh geometry={nodes['Superior_Temporal_Gyrus,_posterior_division'].geometry} material={nodes['Superior_Temporal_Gyrus,_posterior_division'].material} />
      <mesh geometry={nodes['Middle_Temporal_Gyrus,_anterior_division'].geometry} material={nodes['Middle_Temporal_Gyrus,_anterior_division'].material} />
      <mesh geometry={nodes['Middle_Temporal_Gyrus,_posterior_division'].geometry} material={nodes['Middle_Temporal_Gyrus,_posterior_division'].material} />
      <mesh geometry={nodes['Middle_Temporal_Gyrus,_temporooccipital_part'].geometry} material={nodes['Middle_Temporal_Gyrus,_temporooccipital_part'].material} />
      <mesh geometry={nodes['Inferior_Temporal_Gyrus,_anterior_division'].geometry} material={nodes['Inferior_Temporal_Gyrus,_anterior_division'].material} />
      <mesh geometry={nodes['Inferior_Temporal_Gyrus,_posterior_division'].geometry} material={nodes['Inferior_Temporal_Gyrus,_posterior_division'].material} />
      <mesh geometry={nodes['Inferior_Temporal_Gyrus,_temporooccipital_part'].geometry} material={nodes['Inferior_Temporal_Gyrus,_temporooccipital_part'].material} />
      <mesh geometry={nodes.Postcentral_Gyrus.geometry} material={nodes.Postcentral_Gyrus.material} />
      <mesh geometry={nodes.Superior_Parietal_Lobule.geometry} material={nodes.Superior_Parietal_Lobule.material} />
      <mesh geometry={nodes['Supramarginal_Gyrus,_anterior_division'].geometry} material={nodes['Supramarginal_Gyrus,_anterior_division'].material} />
      <mesh geometry={nodes['Supramarginal_Gyrus,_posterior_division'].geometry} material={nodes['Supramarginal_Gyrus,_posterior_division'].material} />
      <mesh geometry={nodes.Angular_Gyrus.geometry} material={nodes.Angular_Gyrus.material} />
      <mesh geometry={nodes['Lateral_Occipital_Cortex,_superior_division'].geometry} material={nodes['Lateral_Occipital_Cortex,_superior_division'].material} />
      <mesh geometry={nodes['Lateral_Occipital_Cortex,_inferior_division'].geometry} material={nodes['Lateral_Occipital_Cortex,_inferior_division'].material} />
      <mesh geometry={nodes.Intracalcarine_Cortex.geometry} material={nodes.Intracalcarine_Cortex.material} />
      <mesh geometry={nodes.Frontal_Medial_Cortex.geometry} material={nodes.Frontal_Medial_Cortex.material} />
      <mesh geometry={nodes['Juxtapositional_Lobule_Cortex_(formerly_Supplementary_Motor_Cortex)'].geometry} material={nodes['Juxtapositional_Lobule_Cortex_(formerly_Supplementary_Motor_Cortex)'].material} />
      <mesh geometry={nodes.Subcallosal_Cortex.geometry} material={nodes.Subcallosal_Cortex.material} />
      <mesh geometry={nodes.Paracingulate_Gyrus.geometry} material={nodes.Paracingulate_Gyrus.material} />
      <mesh geometry={nodes['Cingulate_Gyrus,_anterior_division'].geometry} material={nodes['Cingulate_Gyrus,_anterior_division'].material} />
      <mesh geometry={nodes['Cingulate_Gyrus,_posterior_division'].geometry} material={nodes['Cingulate_Gyrus,_posterior_division'].material} />
      <mesh geometry={nodes.Precuneous_Cortex.geometry} material={nodes.Precuneous_Cortex.material} />
      <mesh geometry={nodes.Cuneal_Cortex.geometry} material={nodes.Cuneal_Cortex.material} />
      <mesh geometry={nodes.Frontal_Orbital_Cortex.geometry} material={nodes.Frontal_Orbital_Cortex.material} />
      <mesh geometry={nodes['Parahippocampal_Gyrus,_anterior_division'].geometry} material={nodes['Parahippocampal_Gyrus,_anterior_division'].material} />
      <mesh geometry={nodes['Parahippocampal_Gyrus,_posterior_division'].geometry} material={nodes['Parahippocampal_Gyrus,_posterior_division'].material} />
      <mesh geometry={nodes.Lingual_Gyrus.geometry} material={nodes.Lingual_Gyrus.material} />
      <mesh geometry={nodes['Temporal_Fusiform_Cortex,_anterior_division'].geometry} material={nodes['Temporal_Fusiform_Cortex,_anterior_division'].material} />
      <mesh geometry={nodes['Temporal_Fusiform_Cortex,_posterior_division'].geometry} material={nodes['Temporal_Fusiform_Cortex,_posterior_division'].material} />
      <mesh geometry={nodes.Temporal_Occipital_Fusiform_Cortex.geometry} material={nodes.Temporal_Occipital_Fusiform_Cortex.material} />
      <mesh geometry={nodes.Occipital_Fusiform_Gyrus.geometry} material={nodes.Occipital_Fusiform_Gyrus.material} />
      <mesh geometry={nodes.Frontal_Opercular_Cortex.geometry} material={nodes.Frontal_Opercular_Cortex.material} />
      <mesh geometry={nodes.Central_Opercular_Cortex.geometry} material={nodes.Central_Opercular_Cortex.material} />
      <mesh geometry={nodes.Parietal_Opercular_Cortex.geometry} material={nodes.Parietal_Opercular_Cortex.material} />
      <mesh geometry={nodes.Planum_Polare.geometry} material={nodes.Planum_Polare.material} />
      <mesh geometry={nodes["Heschl's_Gyrus_(includes_H1_and_H2)"].geometry} material={nodes["Heschl's_Gyrus_(includes_H1_and_H2)"].material} />
      <mesh geometry={nodes.Planum_Temporale.geometry} material={nodes.Planum_Temporale.material} />
      <mesh geometry={nodes.Supracalcarine_Cortex.geometry} material={nodes.Supracalcarine_Cortex.material} />
      <mesh geometry={nodes.Occipital_Pole.geometry} material={nodes.Occipital_Pole.material} />
    </group>
  )
}

useGLTF.preload('/brain_model.glb')
