/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/full_brain_model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model({ isAdvanced = false, ...props }) {
  const { nodes } = useGLTF('/full_brain_model.glb')

  // Array of cortical region names (the outer shell parts)
  const corticalRegions = [
    'Frontal_Pole',
    'Insular_Cortex',
    'Superior_Frontal_Gyrus',
    'Middle_Frontal_Gyrus',
    'Inferior_Frontal_Gyrus,_pars_triangularis',
    'Inferior_Frontal_Gyrus,_pars_opercularis',
    'Precentral_Gyrus',
    'Temporal_Pole',
    'Superior_Temporal_Gyrus,_anterior_division',
    'Superior_Temporal_Gyrus,_posterior_division',
    'Middle_Temporal_Gyrus,_anterior_division',
    'Middle_Temporal_Gyrus,_posterior_division',
    'Middle_Temporal_Gyrus,_temporooccipital_part',
    'Inferior_Temporal_Gyrus,_anterior_division',
    'Inferior_Temporal_Gyrus,_posterior_division',
    'Inferior_Temporal_Gyrus,_temporooccipital_part',
    'Postcentral_Gyrus',
    'Superior_Parietal_Lobule',
    'Supramarginal_Gyrus,_anterior_division',
    'Supramarginal_Gyrus,_posterior_division',
    'Angular_Gyrus',
    'Lateral_Occipital_Cortex,_superior_division',
    'Lateral_Occipital_Cortex,_inferior_division',
    'Intracalcarine_Cortex',
    'Frontal_Medial_Cortex',
    'Juxtapositional_Lobule_Cortex_(formerly_Supplementary_Motor_Cortex)',
    'Subcallosal_Cortex',
    'Paracingulate_Gyrus',
    'Cingulate_Gyrus,_anterior_division',
    'Cingulate_Gyrus,_posterior_division',
    'Precuneous_Cortex',
    'Cuneal_Cortex',
    'Frontal_Orbital_Cortex',
    'Parahippocampal_Gyrus,_anterior_division',
    'Parahippocampal_Gyrus,_posterior_division',
    'Lingual_Gyrus',
    'Temporal_Fusiform_Cortex,_anterior_division',
    'Temporal_Fusiform_Cortex,_posterior_division',
    'Temporal_Occipital_Fusiform_Cortex',
    'Occipital_Fusiform_Gyrus',
    'Frontal_Opercular_Cortex',
    'Central_Opercular_Cortex',
    'Parietal_Opercular_Cortex',
    'Planum_Polare',
    "Heschl's_Gyrus_(includes_H1_and_H2)",
    'Planum_Temporale',
    'Supracalcarine_Cortex',
    'Occipital_Pole',
    'Left_Cerebral_White_Matter',
    'Left_Cerebral_Cortex',
    'Right_Cerebral_White_Matter',
    'Right_Cerebral_Cortex',
  ]

  return (
    <group position={[-91.5, -110.0, -78.1]} {...props} dispose={null}>
      {Object.entries(nodes).map(([name, node]) => {
        if (!node?.geometry) return null
        const isCortical = corticalRegions.includes(name)
        return (
          <mesh key={name} name={name} geometry={node.geometry}>
            {isCortical ? (
              <meshStandardMaterial
                transparent={true}
                opacity={isAdvanced ? 0.15 : 1}
                flatShading={false}
              />
            ) : (
              <meshStandardMaterial
                transparent={false}
                opacity={1}
                flatShading={false}
              />
            )}
          </mesh>
        )
      })}
    </group>
  )
}

useGLTF.preload('/full_brain_model.glb')
