/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/full_brain_model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { ANATOMY_DATA } from './anatomyData.js'

// Backwards-compatible export mapping mesh names to their functional display names
export const functionalAliases = Object.fromEntries(
  Object.entries(ANATOMY_DATA).map(([k, v]) => [k, v.displayName])
)

export function Model({
  currentStage = 'macro',
  activeGroup = 'Frontal',
  selectedMesh = null,
  onSelectMesh,
  onSelectGroup,
  ...props
}) {
  const { nodes } = useGLTF('/full_brain_model.glb')

  return (
    <group position={[-91.5, -110.0, -78.1]} {...props} dispose={null}>
      {Object.entries(nodes).map(([name, node]) => {
        if (!node?.geometry) return null

        // Hide duplicate general cerebral shell geometry to avoid raycast occlusion of specific gyri and deep core
        if (name.includes('Cerebral')) return null

        const anatomy = ANATOMY_DATA[name] || {}
        const parentGroup = anatomy.parentGroup || 'Subcortical'
        const isCorticalLobe = ['Frontal', 'Parietal', 'Temporal', 'Occipital'].includes(parentGroup)

        // ==========================================
        // 1. DEEP CORE STAGE
        // ==========================================
        if (currentStage === 'deep_core') {
          // Hide all 4 cortical lobes completely
          if (isCorticalLobe) {
            return null
          }

          // Subcortical and cerebellar structures are fully exposed
          const isSelected = selectedMesh === name

          return (
            <mesh
              key={name}
              name={name}
              geometry={node.geometry}
              castShadow
              receiveShadow
              onClick={(e) => {
                e.stopPropagation()
                onSelectMesh?.(name)
              }}
            >
              {isSelected ? (
                <meshPhysicalMaterial
                  color="#ffd700"
                  roughness={0.3}
                  metalness={0.2}
                  clearcoat={0.8}
                  clearcoatRoughness={0.1}
                />
              ) : (
                <meshPhysicalMaterial
                  color="#9ca3af"
                  roughness={0.65}
                  metalness={0.1}
                  clearcoat={0.1}
                />
              )}
            </mesh>
          )
        }

        // ==========================================
        // 2. LOBE FOCUS STAGE
        // ==========================================
        if (currentStage === 'lobe_focus') {
          const isMemberOfActiveGroup = parentGroup === activeGroup

          if (!isMemberOfActiveGroup) {
            // Drop other cortical, cerebellar, and subcortical meshes to faint ghost silhouette (opacity 0.05)
            // raycast={() => null} ensures clicks never get blocked by ghost meshes
            return (
              <mesh
                key={name}
                name={name}
                geometry={node.geometry}
                raycast={() => null}
              >
                <meshPhysicalMaterial
                  color="#9ca3af"
                  roughness={0.8}
                  transparent={true}
                  opacity={0.05}
                  depthWrite={false}
                />
              </mesh>
            )
          }

          // Meshes belonging to activeGroup are fully opaque and individually clickable
          const isSelected = selectedMesh === name

          return (
            <mesh
              key={name}
              name={name}
              geometry={node.geometry}
              castShadow
              receiveShadow
              onClick={(e) => {
                e.stopPropagation()
                onSelectMesh?.(name)
              }}
            >
              {isSelected ? (
                <meshPhysicalMaterial
                  color="#00e5ff"
                  roughness={0.3}
                  metalness={0.2}
                  clearcoat={0.8}
                  clearcoatRoughness={0.1}
                />
              ) : (
                <meshPhysicalMaterial
                  color="#ffd2a8"
                  roughness={0.3}
                  metalness={0.2}
                  clearcoat={0.8}
                  clearcoatRoughness={0.1}
                />
              )}
            </mesh>
          )
        }

        // ==========================================
        // 3. MACRO STAGE (Overview)
        // ==========================================
        const isGroupActive = parentGroup === activeGroup

        return (
          <mesh
            key={name}
            name={name}
            geometry={node.geometry}
            castShadow
            receiveShadow
            onClick={(e) => {
              e.stopPropagation()
              onSelectGroup?.(parentGroup)
            }}
          >
            {isGroupActive ? (
              <meshPhysicalMaterial
                color="#ffd2a8"
                roughness={0.3}
                metalness={0.2}
                clearcoat={0.8}
                clearcoatRoughness={0.1}
              />
            ) : (
              <meshPhysicalMaterial
                color="#9ca3af"
                roughness={0.65}
                metalness={0.1}
                clearcoat={0.1}
              />
            )}
          </mesh>
        )
      })}
    </group>
  )
}

useGLTF.preload('/full_brain_model.glb')
